config/routes.rb
Hcrc::Application.routes.draw do
  root :to => "catalog#index"

  Blacklight.add_routes(self)

  devise_for :users

end

app/controllers/catalog_controller.rb
# -*- encoding : utf-8 -*-
require 'blacklight/catalog'

class CatalogController < ApplicationController

  include Blacklight::Catalog

  configure_blacklight do |config|
    ## Default parameters to send to solr for all search-like requests. See also SolrHelper#solr_search_params
    config.default_solr_params = {
      :qt => 'search',
      :rows => 10
    }

    ## Default parameters to send on single-document requests to Solr. These settings are the Blackligt defaults (see SolrHelper#solr_doc_params) or
    ## parameters included in the Blacklight-jetty document requestHandler.
    #
    #config.default_document_solr_params = {
    #  :qt => 'document',
    #  ## These are hard-coded in the blacklight 'document' requestHandler
    #  # :fl => '*',
    #  # :rows => 1
    #  # :q => '{!raw f=id v=$id}'
    #}

    #config for xmlitem webservice JSP 05/16/2012
    config.xmlitem_url = 'http://libexp.uits.iu.edu/xmlitem2.cgi?key='

    # solr field configuration for search results/index views
    config.index.show_link = 'title'
    config.index.record_display_type = 'type'

    # solr field configuration for document/show views
    config.show.html_title = 'title'
    config.show.heading = 'title'
    config.show.display_type = 'type'

    # solr fields that will be treated as facets by the blacklight application
    #   The ordering of the field names is the order of the display
    #
    # Setting a limit will trigger Blacklight's 'more' facet values link.
    # * If left unset, then all facet values returned by solr will be displayed.
    # * If set to an integer, then "f.somefield.facet.limit" will be added to
    # solr request, with actual solr request being +1 your configured limit --
    # you configure the number of items you actually want _displayed_ in a page.
    # * If set to 'true', then no additional parameters will be sent to solr,
    # but any 'sniffed' request limit parameters will be used for paging, with
    # paging at requested limit -1. Can sniff from facet.limit or
    # f.specific_field.facet.limit solr request params. This 'true' config
    # can be used if you set limits in :default_solr_params, or as defaults
    # on the solr side in the request handler itself. Request handler defaults
    # sniffing requires solr requests to be made with "echoParams=all", for
    # app code to actually have it echo'd back to see it.
    #
    # :show may be set to false if you don't want the facet to be drawn in the
    # facet bar
    config.add_facet_field 'language', :label => 'Language', :limit => 20
    config.add_facet_field 'author_facet', :label => 'Author', :limit => 10
    config.add_facet_field 'corp_author_facet', :label => 'Corporate Author', :limit => 10
    config.add_facet_field 'year', :label => 'Year', :range => true
    config.add_facet_field 'state_country_facet', :label => 'State/Country', :limit => 10
    config.add_facet_field 'grade_level_group_facet', :label => 'Grade Level Group', :query => {
    :grade_level_group_prek => { :label => 'Pre-K', :fq => "grade_level_group:Pre-K"},
    :grade_level_group_kinder => { :label => 'Kindergarten', :fq => "grade_level_group:Kindergarten"},
    :grade_level_group_elementary => { :label => 'Elementary', :fq => "grade_level_group:Elementary"},
    :grade_level_group_middle => { :label => 'Middle school', :fq => "grade_level_group:Middle"},
    :grade_level_group_high => { :label => 'High school', :fq => "grade_level_group:High"},
    :grade_level_group_post => { :label => 'Postsecondary', :fq => "grade_level_group:Postsecondary"},
    }
    config.add_facet_field 'grade_level_number_facet', :label => 'Grade Level Number', :query => {
    :grade_level_number_kinder => { :label => 'Kindergarten', :fq => "grade_level_number:Kindergarten"},
    :grade_level_number_first => { :label => '1st grade', :fq => "grade_level_number:1st*"},
    :grade_level_number_second => { :label => '2nd grade', :fq => "grade_level_number:2nd*"},
    :grade_level_number_third => { :label => '3rd grade', :fq => "grade_level_number:3rd*"},
    :grade_level_number_fourth => { :label => '4th grade', :fq => "grade_level_number:4th*"},
    :grade_level_number_fifth => { :label => '5th grade', :fq => "grade_level_number:5th*"},
    :grade_level_number_sixth => { :label => '6th grade', :fq => "grade_level_number:6th*"},
    :grade_level_number_seventh => { :label => '7th grade', :fq => "grade_level_number:7th*"},
    :grade_level_number_eighth => { :label => '8th grade', :fq => "grade_level_number:8th*"},
    :grade_level_number_ninth => { :label => '9th grade', :fq => "grade_level_number:9th*"},
    :grade_level_number_tenth => { :label => '10th grade', :fq => "grade_level_number:10th*"},
    :grade_level_number_eleventh => { :label => '11th grade', :fq => "grade_level_number:11th*"},
    :grade_level_number_twelfth => { :label => '12th grade', :fq => "grade_level_number:12th*"},
    :grade_level_number_post => { :label => 'Postsecondary', :fq => "grade_level_number:Postsecondary"},
    }
	config.add_facet_field 'keywords_facet', :label => 'Subjects', :limit => 10



    # Have BL send all facet field names to Solr, which has been the default
    # previously. Simply remove these lines if you'd rather use Solr request
    # handler defaults, or have no facets.
    config.add_facet_fields_to_solr_request!

    # solr fields to be displayed in the index (search results) view
    #   The ordering of the field names is the order of the display
    config.add_index_field 'title', :label => 'Title:'
	config.add_index_field 'author_nat', :label => 'Author:'
    config.add_index_field 'corp_author', :label => 'Corporate Author:'
    config.add_index_field 'year', :label => 'Date:'
    config.add_index_field 'state_country', :label => 'State/Country:'
    config.add_index_field 'grade_level_group', :label => 'Grade Level:'
    config.add_index_field 'keywords', :label => 'Subjects:'

    # solr fields to be displayed in the show (single result) view
    #   The ordering of the field names is the order of the display
    config.add_show_field 'title', :label => 'Title:'
    config.add_show_field 'series_title', :label => 'Series Title:'
    config.add_show_field 'type', :label => 'Type:'
    config.add_show_field 'author_nat', :label => 'Author(s):'
    config.add_show_field 'corp_author', :label => 'Corporate Author:'
    config.add_show_field 'date', :label => 'Date:'
    config.add_show_field 'publisher', :label => 'Publisher:'
    config.add_show_field 'pub_place', :label => 'Place of Publication:'
    config.add_show_field 'pages', :label => 'Number of Pages:'
    config.add_show_field 'notes', :label => 'Notes:'
    config.add_show_field 'abstract', :label => 'Abstract:'
    config.add_show_field 'call_number', :label => 'Call Number:'
    config.add_show_field 'state_country', :label => 'State/Country:'
    config.add_show_field 'series_vol', :label => 'Series Volume Number:'
    config.add_show_field 'series_num_vol', :label => 'Number of Volumes in Series:'
    config.add_show_field 'edition', :label => 'Edition:'
    config.add_show_field 'issue', :label => 'Issue:'
    config.add_show_field 'keywords', :label => 'Subjects:', :link_to_search => :keywords_facet
    config.add_show_field 'language', :label => 'Language:'
    config.add_show_field 'grade_level_group', :label => 'Grade Level Group:'
    config.add_show_field 'grade_level_number', :label => 'Grade Level Number:', :link_to_search => :grade_level_number_facet


    # "fielded" search configuration. Used by pulldown among other places.
    # For supported keys in hash, see rdoc for Blacklight::SearchFields
    #
    # Search fields will inherit the :qt solr request handler from
    # config[:default_solr_parameters], OR can specify a different one
    # with a :qt key/value. Below examples inherit, except for subject
    # that specifies the same :qt as default for our own internal
    # testing purposes.
    #
    # The :key is what will be used to identify this BL search field internally,
    # as well as in URLs -- so changing it after deployment may break bookmarked
    # urls.  A display label will be automatically calculated from the :key,
    # or can be specified manually to be different.

    # This one uses all the defaults set by the solr request handler. Which
    # solr request handler? The one set in config[:default_solr_parameters][:qt],
    # since we aren't specifying it otherwise.

    config.add_search_field 'all_fields', :label => 'All Fields'


    # Now we see how to over-ride Solr request handler defaults, in this
    # case for a BL "search field", which is really a dismax aggregate
    # of Solr search fields.

    config.add_search_field('title') do |field|
      # solr_parameters hash are sent to Solr as ordinary url query params.
      field.solr_parameters = {
        :'spellcheck.dictionary' => 'title',
        :qf => '${title_qf}',
        :pf => '${title_pf}'
      }
    end

    config.add_search_field('author') do |field|
      field.solr_parameters = {
        :'spellcheck.dictionary' => 'author',
        :qf => '${author_qf}',
        :pf => '${author_pf}'
      }
    end

    # Specifying a :qt only to show it's possible, and so our internal automated
    # tests can test it. In this case it's the same as
    # config[:default_solr_parameters][:qt], so isn't actually neccesary.
    config.add_search_field('corp_author') do |field|
      field.solr_parameters = {
        :'spellcheck.dictionary' => 'corp_author',
        :qf => '${corp_author_qf}',
        :pf => '${corp_author_pf}'
      }
      field.qt = 'search'
    end

    # "sort results by" select (pulldown)
    # label in pulldown is followed by the name of the SOLR field to sort by and
    # whether the sort is ascending or descending (it must be asc or desc
    # except in the relevancy case).
    config.add_sort_field 'relevancy', field: 'score desc, year_sort desc, title_sort asc', :label => 'relevance'

app/views/catalog/_constraints.html.erb
<% if query_has_constraints? %>
      <div id="appliedParams" class="constraints-container">
        <span class="constraints-label"><%= t('blacklight.search.filters.title') %></span>
        <%= render_constraints(params) %>  
        <%=link_to "View Bookmarked Items", :controller => :bookmarks, :action => :index, :id=>"viewBookmarks" %>
        <%= content_tag(:a, " | ") %>
        <%=link_to t('blacklight.search.start_over'), url_for(:action=>'index'), :class => "catalog_startOverLink", :id=>"startOverLink" %>
      </div>
<% end %>

app/views/catalog/_home_text.html.erb
<h4>Welcome to the Cubberley Historical Curriculum Resource Collection</h4>
<p>Cubberley Education Library has a collection of historical curriculum materials and instructional guides published by national, state and local boards, departments of education, as well as other groups devoted to improving instruction.  Request materials in advance for use in the library.</p>
<p>This database is under construction with new records being added on a regular basis.  For requests or information contact us at 650-723-2121 or <a href="mailto:cubberley@stanford.edu">cubberley@stanford.edu.</a></p>
<p>&nbsp;</p>
<h3>Collection Highlights</h3>
<div id="googft-mapCanvas"></div>
  <input id="googft-legend-open" style="display:none" type="button" value="Legend"></input>
  <div id="googft-legend">
    <p id="googft-legend-title">Number of Records in Collection</p>
    <div>
      <img class="googft-paddle-icon" src="http://maps.google.com/mapfiles/ms/micons/yellow-dot.png"/>
      <span class="googft-legend-range">0 to 50</span>
    </div>
    <div>
      <img class="googft-paddle-icon" src="http://maps.google.com/mapfiles/ms/micons/red-dot.png"/>
      <span class="googft-legend-range">50 to 100</span>
    </div>
    <div>
      <img class="googft-paddle-icon" src="http://maps.google.com/mapfiles/ms/micons/green-dot.png"/>
      <span class="googft-legend-range">100 to 200</span>
    </div>
    <div>
      <img class="googft-paddle-icon" src="http://maps.google.com/mapfiles/ms/micons/purple-dot.png"/>
      <span class="googft-legend-range">200 to 500</span>
    </div>
    <div>
      <img class="googft-paddle-icon" src="http://maps.google.com/mapfiles/ms/micons/blue-dot.png"/>
      <span class="googft-legend-range">500 to 3,000</span>
    </div>
    <input id="googft-legend-close" style="display:none" type="button" value="Hide"></input>
  </div>
  
  <h3></h3>
  <div>
  <p>&nbsp;</p>
</div>

app/views/catalog/_previous_next_doc.html.erb
<% #Using the Bootstrap Pagination class  -%>
<% if @previous_document || @next_document %>
	<div class="well" id="previousNextDocument">
    <%= link_to_previous_document @previous_document %> |

    <%= item_page_entry_info %> |

    <%= link_to_next_document @next_document %>

<div class="pull-right">
      <%= link_back_to_catalog %>
      |
      <%=link_to "#{t('blacklight.search.start_over')}", catalog_index_path, :id=>"startOverLink" %>
      |
       <%=link_to "View Bookmarked Items", :controller => :bookmarks, :action => :index, :id=>"viewBookmarks" %>
  </div>
	</div>
<% end %>

app/views/catalog/_show_tools.html.erb
<%-
  # Compare with render_document_functions_partial helper, and
  # _document_functions partial. BL actually has two groups
  # of document-related tools. "document functions" by default
  # contains Bookmark functionality shown on both results and
  # item view. While "document tools" contains external export type
  # functions by default only on detail.

  #Added Bootstrap class well and 'hidden-phone' for the tools-bar 
-%>
  <ul class="nav nav-list">
      <li class="nav-header"><%= t('blacklight.tools.title') %></li>
      <li>
        <%= render_show_doc_actions @document %>
      </li>
  </ul>

app/views/catalog/show.html.erb
<div id="content" class="span9 show-document">

  <%= render 'previous_next_doc' %>
<% sidebar_items << render_document_sidebar_partial %>

<% @page_title = t('blacklight.search.show.title', :document_title => document_show_html_title, :application_name => application_name) %>
<% extra_head_content << render_link_rel_alternates %>


<%# this should be in a partial -%>

<div id="document" class="<%= render_document_class %>">
  <div id="doc_<%= @document.id.to_s.parameterize %>">
  

    <% # bookmark/folder functions -%>
    <%= render_document_heading(:h1).html_safe %>

    
    <div class="document">
      <%= render_document_partial @document, :show %>
    </div>

   
  </div>
</div>



  <% if @document.respond_to?(:export_as_openurl_ctx_kev) %>
    <!-- 
         // COinS, for Zotero among others. 
         // This document_partial_name(@document) business is not quite right,
         // but has been there for a while. 
    -->
    <span class="Z3988" title="<%= @document.export_as_openurl_ctx_kev(document_partial_name(@document)) %>"></span>
  <% end %>

</div>
   <div id="sidebar" class="span3">
   <%= render_document_sidebar_partial  %>
</div><!--/span -->